# Generated by Django 6.0.1 on 2026-02-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('models', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='models.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='models.event'),
        ),
    ]
