# Generated by Django 6.0.1 on 2026-02-28 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_registration_alter_invoice_event'),
        ('models', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='models.registration'),
        ),
    ]
