# Generated by Django 6.0.1 on 2026-02-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='registration',
        ),
    ]
