# Generated by Django 6.0.1 on 2026-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_invoice_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
