# Generated by Django 6.0.1 on 2026-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Modified'), (3, 'Issued'), (4, 'Sent'), (5, 'Partially Paid'), (6, 'Paid'), (7, 'Overdue'), (8, 'Cancelled'), (9, 'Void'), (10, 'Refunded')], default=1),
        ),
    ]
